version: '3.7'

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  # Start docker container for Datacube-Index
  products-tester:
    image: opendatacube/datacube-index:latest 
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - ./dev/products_dev.csv:/conf/products_dev.csv
      - ./prod/products_prod.csv:/conf/products_prod.csv
    command: tail -f /dev/null
