from ows_refactored.common.ows_reslim_cfg import reslim_land_cover

style_colours = {
    "name": "style_colours",
    "title": "Coloured",
    "abstract": "Land cover colours",
    "needed_bands": ["supercell"],
    "index_function": {
        "function": "datacube_ows.band_utils.single_band",
        "mapped_bands": True,
        "kwargs": {
            "band": "supercell",
        },
    },
    "value_map": {
        "supercell": [
            {
                "title": "",
                "abstract": "",
                "values": [0],
                "alpha": 0.0,
                "color": "#707070",
            },
            {
                "title": "Water",
                "abstract": "",
                "values": [1],
                "color": "#419BDF",
            },
            {
                "title": "Trees",
                "abstract": "",
                "values": [2],
                "color": "#397D49",
            },
            {
                "title": "Flooded Vegetation",
                "abstract": "",
                "values": [4],
                "color": "#7A87C6",
            },
            {
                "title": "Crops",
                "abstract": "",
                "values": [5],
                "color": "#E49635",
            },
            {
                "title": "Built Area",
                "abstract": "",
                "values": [7],
                "color": "#C4281B",
            },
            {
                "title": "Bare Ground",
                "abstract": "",
                "values": [8],
                "color": "#A59B8F",
            },
            {
                "title": "Snow/Ice",
                "abstract": "",
                "values": [9],
                "color": "#A8EBFF",
            },
            {
                "title": "Clouds",
                "abstract": "",
                "values": [10],
                "color": "#616161",
            },
            {
                "title": "Rangeland",
                "abstract": "",
                "values": [11],
                "color": "#E3E2C3",
            },
        ]
    },
    "legend": {"width": 3.0, "height": 3.0},
}

layer = {
    "title": "Impact Observatory Land Use/Land Cover",
    "name": "io_lulc_v2",
    "abstract": """
Time series of annual global maps of land use and land cover (LULC), currently available from 2017 to 2023. The maps are derived from ESA Sentinel-2 imagery at 10m resolution. Each map is a composite of LULC predictions for 9 classes throughout the year in order to generate a representative snapshot of each year.

This dataset was generated by Impact Observatory, who used billions of human-labeled pixels (curated by the National Geographic Society) to train a deep learning model for land classification. The global map was produced by applying this model to the Sentinel-2 annual scene collections on the Planetary Computer. Each of the maps has an assessed average accuracy of over 75%.

For more information, see https://planetarycomputer.microsoft.com/dataset/io-lulc-annual-v02.
""",
    "product_name": "io_lulc_v2",
    "time_resolution": "summary",
    "bands": {
        "supercell": [],
    },
    "resource_limits": reslim_land_cover,
    "image_processing": {
        "extent_mask_func": "datacube_ows.ogc_utils.mask_by_val",
        "always_fetch_bands": [],
        "manual_merge": False,
    },
    "native_crs": "EPSG:6933",
    "native_resolution": [
        10.0,
        -10.0,
    ],
    "styling": {
        "default_style": "style_colours",
        "styles": [style_colours],
    },
}
