from ows_refactored.common.ows_reslim_cfg import reslim_land_cover


style_wsf_2015 = {
    "name": "wsf2015",
    "title": "World Settlement Footprint",
    "abstract": "World Settlement Footprint 2015",
    "value_map": {
        "wsf2015": [
            {
                "title": "World Settlement Footprint 2015",
                "color": "#D3D3D3",
                "values": [1],
            }
        ]
    }
}

layer = {
    "title": "World Settlement Footprint 2015",
    "name": "wsf_2015",
    "abstract": """
The World Settlement Footprint WSF 2015 version 2 (WSF2015 v2) is a 10m resolution binary mask outlining the extent of human settlements globally for the year 2015. Specifically, the WSF2015 v2 is a pilot product generated by combining multiple datasets.The World Settlement Footprint (WSF) 2015 derived at 10m spatial resolution by means of 2014-2015 multitemporal Landsat-8 and Sentinel-1 imagery (of which ~217K and ~107K scenes have been processed, respectively). The High Resolution Settlement Layer (HRSL) generated by the Connectivity Lab team at Facebook through the employment of 2016 DigitalGlobe VHR satellite imagery and publicly released at 30m spatial resolution for 214 countries (Marconcini et al., 2020).

For more information, see https://austriaca.at/?arp=0x003c9b4c.
""",
    "product_name": "wsf_2015",
    "time_resolution": "summary",
    "bands": {
        "wsf2015": [],
    },
    "resource_limits": reslim_land_cover,
    "image_processing": {
        "extent_mask_func": "datacube_ows.ogc_utils.mask_by_val",
        "always_fetch_bands": [],
        "manual_merge": False,
    },
    "native_crs": "EPSG:4326",
    "native_resolution": [
        8.983152841195215e-05,
        -8.983152841195215e-05,
    ],
    "styling": {
        "default_style": "style_wsf_2015",
        "styles": [style_wsf_2015],
    },
}
