name : Terria catalog Linting

on:
  push:
    paths:
      - 'terria/**'
      - .github/workflows/linting-json.yml
  pull_request:
    branches: [ master ]
    paths:
      - 'terria/**'
      - .github/workflows/main.yml

jobs:
  jsonlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Run Json Linter
      run: |
        npm install jsonlint -g
        jsonlint terria/africa.json -q
