name: OWS CFG Test

on:
  push:
    path:
      - 'services/**'
      - .github/workflows/ows-cfg.yaml
    pull_request:
      branches: [ master ]
      paths:
        - 'services/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Run Python Linter
      run: |
        python -m pip install pylint boto3
        ./check-code.sh

    - name: Run ows_refactored_cfg test (prod)
      run: |
        docker-compose --log-level DEBUG -f docker-compose.ows.yaml up -d
        docker-compose -f docker-compose.ows.yaml exec -T ows /bin/sh -c "cd /env/config; ./compare-cfg.sh"
        docker-compose -f docker-compose.ows.yaml down
      env:
        OWS_CFG_MOUNT: ./services/ows_refactored
        OWS_INVENTORY_JSON: ./services/inventory/prod/inventory.json
        DATACUBE_OWS_CFG: ows_refactored.prod_ows_root_cfg.ows_cfg
        WMS_CONFIG_FILE: prod_ows_root_cfg.py
        CFG_PATH_PREFIX: /env/config/ows_refactored

    - name: Run ows_cfg test (Prod-af)
      run: |
        docker-compose --log-level DEBUG -f docker-compose.ows.yaml up -d
        docker-compose -f docker-compose.ows.yaml exec -T ows /bin/sh -c "cd /env/config; ./compare-cfg.sh"
        docker-compose -f docker-compose.ows.yaml down
      env:
        OWS_CFG_MOUNT: ./services/ows_refactored
        OWS_INVENTORY_JSON: ./services/inventory/prod_af/inventory.json
        DATACUBE_OWS_CFG: ows_refactored.prod_af_ows_root_cfg.ows_cfg
        WMS_CONFIG_FILE: prod_af_ows_root_cfg.py
        CFG_PATH_PREFIX: /env/config/ows_refactored
