name: OWS CFG Lint and Test

on:
  push:
    paths:
      - 'services/**'
      - .github/workflows/ows_cfg_testing.yaml
  pull_request:
    branches: [ master ]
    paths:
      - 'services/**'
      - .github/workflows/ows_cfg_testing.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: E501
          path: services/ows_refactored

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Test DEV config
      run: |
        docker-compose -f docker-compose.ows.yaml up -d

        docker-compose -f docker-compose.ows.yaml run \
          -e DATACUBE_OWS_CFG=ows_refactored.dev_af_ows_root_cfg.ows_cfg \
          -T ows \
          datacube-ows-cfg check -i /env/config/inventory/dev_af/inventory.json

        docker-compose -f docker-compose.ows.yaml down

    - name: Test PROD config
      run: |
        docker-compose -f docker-compose.ows.yaml up -d

        docker-compose -f docker-compose.ows.yaml run \
          -e DATACUBE_OWS_CFG=ows_refactored.prod_af_ows_root_cfg.ows_cfg \
          -T ows \
          datacube-ows-cfg check -i /env/config/inventory/prod_af/inventory.json

        docker-compose -f docker-compose.ows.yaml down
